namespace SimpleGameApi.Models.Domain.Enums;

public enum SqlQueryEnum
{
    CADASTRAR_VENDAS,
    ATUALIZAR_VENDAS,
    EXCLUIR_VENDAS,
    LISTAR_VENDAS,
    PESQUISAR_VENDAS,

    CADASTRAR_ALUGUEL,
    ATUALIZAR_ALUGUEL,
    EXCLUIR_ALUGUEL,
    LISTAR_ALUGUEL,
    PESQUISAR_ALUGUEL
}
